server:
  port: 8082
#  指定名称
spring:
  application:
    name: global
#数据连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/his_menzhen?useUnicode=true&characterEncoding=utf8

#    时间转换格式
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    时区
    time-zone: GMT+8

#注册中心
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka


feign:
  hystrix:
    enabled: true


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
#  自动将下划线转换为驼峰
    map-underscore-to-camel-case: true
# 启动feign的熔断器功能
